name: Build & Publish

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Build with Maven
        # This is a workaround to fix the SSL certificate issue with the Maven repository
        run: mvn clean verify --batch-mode --file pom.xml -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true -Dmaven.resolver.transport=wagon

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Build with Maven
      # This is a workaround to fix the SSL certificate issue with the Maven repository
        run: mvn clean verify --batch-mode --file pom.xml -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true -Dmaven.resolver.transport=wagon

      - name: Set settings.xml
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "mks-repo",
              "username": "${{ secrets.MAVEN_USERNAME }}",
              "password": "${{ secrets.MAVEN_TOKEN }}"
            },
            {
              "id": "mks-repo-snapshots",
              "username": "${{ secrets.MAVEN_USERNAME }}",
              "password": "${{ secrets.MAVEN_TOKEN }}"
            }]

      - name: Publish
        # This is a workaround to fix the SSL certificate issue with the Maven repository
        run: mvn --batch-mode deploy -DskipTests -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true -Dmaven.resolver.transport=wagon
